# Generated by Django 4.1.1 on 2022-09-06 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('pick_up_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('drop_off_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('pick_up_time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
