# Generated by Django 4.1.1 on 2022-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='load_number',
            field=models.CharField(default=289495, max_length=255),
        ),
    ]
